create table Item
(
IdItem int generated by default as identity start with 1
    minvalue 1 
    maxvalue 1000000
    increment by 1
    cache 20
    primary key,
Name varchar(50) not null,
Cost float not null CHECK (Cost >= 0),
IsDeleted CHAR(1) CHECK (IsDeleted IN ('1','0'))
);

create table UserInCaffe
(
IdUser int generated by default as identity start with 1
    minvalue 1 
    maxvalue 1000000
    increment by 1
    cache 20
    primary key,
Name varchar(50) not null,
Login varchar(50) not null,
Password varchar(50) not null,
Phone varchar(10) not null,
Created date not null,
DateOfBirth date not null,
Status varchar(50) default 'user' not null,
IsDeleted CHAR(1) CHECK (IsDeleted IN ('1','0'))
);


CREATE TABLE OrderInCaffe
(
IdOrder int generated by default as identity start with 1
    minvalue 1 
    maxvalue 1000000
    increment by 1
    cache 20
    primary key,
IdUser int,
Created date not null,
Discount float not null,
IsDeleted CHAR(1) CHECK (IsDeleted IN ('1','0')),
CONSTRAINT FK_IdUser
    FOREIGN KEY (IdUser)
    REFERENCES UserInCaffe(IdUser)
);


create table ItemsInOrder
(
ItemsInOrder int generated by default as identity start with 1
    minvalue 1 
    maxvalue 1000000
    increment by 1
    cache 20
    primary key,
IdOrder int,
IdItem int,
Count NUMBER(10,2) NOT NULL CHECK (Count >= 0),
CONSTRAINT FK_IdOrder
    FOREIGN KEY (IdOrder)
    REFERENCES OrderInCaffe(IdOrder),
CONSTRAINT FK_IdItem
    FOREIGN KEY (IdItem)
    REFERENCES Item(IdItem)
);

create table StatusInCaffe
(
Status int primary key, 
name varchar(50)
);
